api-server:
  image: harbor.tango.rid-intrasoft.eu/api-server
  imageTag: latest
  pullPolicy: Always
  namespace: ips-testing1
  
  imagePullSecrets:
    - name: harborsecretapi

  containerPort: 5000
      
ingress:
  host: example.com
  tlsSecret: my-tls-secret
