apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-server-service-cert
  namespace: ips
spec:
  secretName: api-server-tls-secret
  issuerRef:
    name: letsencrypt-fiware-eks
    kind: ClusterIssuer
  dnsNames:
    - api-server.testing1.k8s-cluster.tango.rid-intrasoft.eu
