apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    namespace: {{ .Values.apiserver.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.apiserver.image }}:{{ .Values.apiserver.imageTag }}
          imagePullPolicy: {{ .Values.apiserver.pullPolicy }}
          ports:
            - containerPort: {{ .Values.apiserver.containerPort }}
      imagePullSecrets:
        {{- toYaml .Values.apiserver.imagePullSecrets | nindent 8 }}



