apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /resource/$2 
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /resource(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-server-service
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}

