apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # El puerto externo
      targetPort: 5000 # El puerto del contenedor
  selector:
    app: {{ .Release.Name }}
